// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DragFile: typeof import('./src/components/DragFile.vue')['default']
    GifItemLoad: typeof import('./src/components/GifItemLoad.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
  }
}
